# Generated by Django 5.2.3 on 2025-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0015_rename_ethnic_background_participant_ethnic_background_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='any_other_background_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
