# Generated by Django 5.2.3 on 2025-07-03 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_merge_20250620_1113'),
        ('participants', '0015_rename_ethnic_background_participant_ethnic_background_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantReportedMammogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(choices=[('NHS_BREAST_SCREENING_UNIT', 'At an NHS breast screening unit'), ('ELSEWHERE_UK', 'Elsewhere in the UK'), ('OUTSIDE_UK', 'Outside the UK'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')])),
                ('location_details', models.TextField(blank=True, default='')),
                ('exact_date', models.DateField(blank=True, null=True)),
                ('approx_date', models.CharField(blank=True, default='')),
                ('different_name', models.CharField(blank=True, default='')),
                ('additional_information', models.TextField(blank=True, default='')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_mammograms', to='participants.participant')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinics.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
